### PR TITLE
Packaging electricity-cost-calculator and preparing for Python 3

### PR DESCRIPTION
**Pull request by gtfierro**
This uses [poetry](https://poetry.eustace.io/) to package the code together and publish it on PyPi so it is easier to work with and update.

I'm also starting the conversion to Python 3 so that this can be used after 2020 :)

The "example" file seems to work okay, but I'm not quite sure how to test the rest of this functionality. To this end, I've published a test package version of this for testing. You can test it with "pip install electricitycostcalculator-gabetest" 

Example:

```python
from electricitycostcalculator_gabetest.cost_calculator.cost_calculator import CostCalculator
# and so on
```

### CODE REVIEW

**Comment by gtfierro** [comment]
According to @jleyden, the package seems to be working OK.

@olivancu do you want me to handle the publishing of the PyPi package (under a non `_gabetest` name?), or do you want to do it? You will need to create a PyPi account and adjust the pyproject.toml file appropriately.

**Comment by olivancu** [comment]
@gtfierro I have published the package: https://pypi.org/project/electricitycostcalculator/

Could you double-check if this works? Thanks a lot for your help

**Comment by gtfierro** [comment]
@jleyden can you give it a try?

**Comment by jleyden** [comment]
@gtfierro all working!

**Pull request merged**
